DNS 내용 추가했습니다.
integraldx/HowToSNUCSE pull request #18
Opened 2019-05-28 07:34 UTC by ryul99

나름대로 찾아보면서 DNS관련 내용 추가했는데 잘못되거나 빠진 내용이 있을 수 있습니다.

2019-06-08 15:58 UTC, nevivurn requested changes
대부분 내용은 맞는데 recursive lookup을 하는 절차에서 다음 DNS 서버를 가리키는 것으로 고치면 좋을 것 같습니다.

2019-06-08 15:58 UTC, nevivurn commented on 기초_지식/network/dns.md
> +2. root domain의 name server에 가서 `martini.snucse.org`를 요청합니다.
root와 중간에 거치는 모든 DNS 서버들은 사용자 요청을 전달한다기보다 요청을 처리할 수 있는 서버를 가리키고 사용자가 이 서버에 다시 요청을 보낸다고 설명하는 것이 더 정확합니다.
![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Example_of_an_iterative_DNS_resolver.svg/563px-Example_of_an_iterative_DNS_resolver.svg.png)

2019-06-08 17:15 UTC, ryul99 commented on 기초_지식/network/dns.md
> +2. root domain의 name server에 가서 `martini.snucse.org`를 요청합니다.
코멘트 감사합니다 고쳐서 커밋하겠습니다ㅎㅎ

2019-06-10 11:08 UTC, nevivurn approved these changes

2019-06-10 11:08 UTC, merged