Git 간단 튜토리얼
integraldx/HowToSNUCSE pull request #20
Opened 2019-07-10 04:26 UTC by integraldx

일단 기본적인 사항만 적어놓았습니다.

2019-07-10 04:27 UTC, integraldx commented
rebase 하느라 좀 커밋이 더러운데 squash 잘 부탁드려요

2019-07-21 23:39 UTC, nevivurn requested changes

2019-07-21 23:39 UTC, nevivurn commented on 개발_환경/Git/files.md
> +또는, 만약 가한 수정사항을 이전으로 되돌리고 싶다면, `git reset`이나 `git checkout -- <file>`명렁을 통해 **Unmodified** 상태로 되돌릴 수 있습니다.
`git reset` 은 기본적으로 staged->modified만 합니다
`git-reset(1)`: "This means that git reset <paths> is the opposite of git add <paths>."

2019-07-21 23:39 UTC, nevivurn commented on 개발_환경/Git/files.md
> +## Staged
많은 문서에서 (manpage 등) "index" 이라는 단어를 사용하기 때문에 "index" 도 언급하는 것이 좋을 것 같습니다. git add == add to index == staging

2019-07-24 09:50 UTC, integraldx commented on 개발_환경/Git/files.md
> +또는, 만약 가한 수정사항을 이전으로 되돌리고 싶다면, `git reset`이나 `git checkout -- <file>`명렁을 통해 **Unmodified** 상태로 되돌릴 수 있습니다.
reset 언급 없앴습니다

2019-07-24 14:35 UTC, nevivurn approved these changes

2019-07-24 14:35 UTC, merged