Markup Language
integraldx/HowToSNUCSE pull request #26
Opened 2020-01-30 10:08 UTC by coffeetea99

마크업 언어 - 마크다운, HTML에 대한 내용 추가

2020-01-30 12:59 UTC, nevivurn requested changes

2020-01-30 12:59 UTC, nevivurn commented on 기초_지식/markup_language/html.md
> +HTML은 웹 브라우저가 작동하는 방식과 밀접한 관련이 있습니다. 컴퓨터 간에 통신을 할 때 모든 정보는 0과 1을 기반으로 하는 문자열로 전송됩니다. 그렇다면 문자열이 어떤 과정을 거쳐 시각적인 웹 페이지로 표시되는 걸까요? 예를 들어 [www.google.com](www.google.com)에 들어가면 어떻게 한가운데에 로고가 있고, 그 아래에 검색창
웹 패이지에서의 element의 위치가 HTML로 지정된다고 하는 것은 부적절하다고 생각합니다. 내용의 구조를 정한다는 것을 더 강조하는것이 나을듯. (위치 등의 styling은 CSS)

2020-01-30 12:59 UTC, nevivurn commented on 기초_지식/markup_language/html.md
> +HTML을 어떻게 보여 줄 지를 정의할 뿐 프로그래밍 언어가 아니기 때문에, HTML만 가지고 할 수 있는 작업은 극히 적습니다. 예를 들어, 어떤 `<button>` element를 클릭했을 때마다 `<h1>` element가 하나씩 생성되게 하는 것조차 HTML만 가지고는 할 수 없습니다. 다른 언어와 연동시켜 element를 생성해야 합니다.
웹 패이지의 내용/구조: HTML
이를 어떻게 보여줄 지: CSS

2020-01-30 12:59 UTC, nevivurn commented on 기초_지식/markup_language/markdown.md
> +마크다운 형식으로 문서를 작성한 다음 마크다운 변환기를 통해 PDF나 HTML 등으로 변환시킬 수 있습니다. vscode로 `.md` 확장자를 갖는 마크다운 파일을 편집하고 있을 땐 우측 상단에 `측면에서 미리 보기 열기` 버튼을 눌러 현재 마크다운 파일이 어떻게 변환될 지 미리 볼 수 있습니다. 또는 [온라인 프로그램](https://dillinger.
표준 비슷한 것이 개발되고 있습니다. https://commonmark.org/

2020-01-30 12:59 UTC, nevivurn commented on 기초_지식/markup_language/markdown.md
> +github에서는 마크다운을 자주 사용합니다. 지금 보고 있는 페이지도 마크다운으로 작성한 것입니다. issue나 comment 등을 마크다운 형식으로 작성할 수 있습니다. README.md라고 이름을 붙인 마크다운 파일이 있으면 자동으로 열어서 보여 줍니다.
*폴더에 들어가면* 자동으로 readme를 보여준다는 설명이 있으면 좋겠습니다.

2020-01-30 12:59 UTC, nevivurn commented on 기초_지식/markup_language/markdown.md
> +마크다운에서 개행문자(enter) 하나만으로는 개행이 되지 않습니다. 개행 문자 뒤에 스페이스바 두 개를 입력해야 합니다.
혹은 empty line. (개인 취향일수도 있습니다.)

2020-01-30 12:59 UTC, nevivurn commented on 기초_지식/markup_language/markdown.md
> +`*` 또는 `+` 또는 `-`를 사용하여 항목의 리스트를 작성할 수 있습니다. 하위 항목은 `TAB`을 입력해 들여쓰기하면 작성할 수 있습니다.
Space도 사용 가능합니다. 예시가 space으로 작성되어 있으니 space도 언급하거나 예시를 tab으로 바꾸는 것이 좋을 것 같습니다.

2020-01-31 04:39 UTC, coffeetea99 commented
HTML이 내용의 구조를 보여 주는 것은 맞으나 마크업 언어가 생소한 사람들은 '내용의 구조'라는 말을 잘 이해하지 못할 수 있다고 생각합니다. 따라서 일단 '무엇을 보여 줄 지를 정한다'라고 서술하겠습니다. 물론 이를 '어떻게' 보여 줄 지는 css의 역할이라고 서술했습니다.

2020-01-31 11:00 UTC, nevivurn approved these changes

2020-01-31 11:01 UTC, merged